on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Publish Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build solution
        run: dotnet build

      - name: Publish app
        run: |
          dotnet publish WinToLinux.slnx -p:PublishSingleFile=true -c Release --sc false --arch x64
          dotnet publish WinToLinux.slnx -p:PublishSingleFile=true -c Release --sc false --arch x86
          dotnet publish WinToLinux.slnx -p:PublishSingleFile=true -c Release --sc false --arch arm64

      - name: Zip published output
        run: |
          Compress-Archive -Path ./bin/Release/*/win-x64/publish -DestinationPath WinToLinux_x64.zip
          Compress-Archive -Path ./bin/Release/*/win-x86/publish -DestinationPath WinToLinux_x86.zip
          Compress-Archive -Path ./bin/Release/*/win-arm64/publish -DestinationPath WinToLinux_arm64.zip

      - name: Rename .exe output
        run: |
          New-Item -ItemType Directory -Force -Path artifacts
          Move-Item -Path ./bin/Release/*/win-x64/publish/WinToLinux.exe -Destination ./artifacts/WinToLinux-x64.exe
          Move-Item -Path ./bin/Release/*/win-x86/publish/WinToLinux.exe -Destination ./artifacts/WinToLinux-x86.exe
          Move-Item -Path ./bin/Release/*/win-arm64/publish/WinToLinux.exe -Destination ./artifacts/WinToLinux-arm64.exe
        shell: pwsh

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/WinToLinux-x64.exe
            ./artifacts/WinToLinux-x86.exe
            ./artifacts/WinToLinux-arm64.exe
            WinToLinux_x64.zip
            WinToLinux_x86.zip
            WinToLinux_arm64.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
